name: credit_module_challenge_build
services:
  config-server:
    image: gradle:jdk21-alpine
    command:
      - gradle
      - --no-daemon
      - clean
      - build
    working_dir: config-server
    volumes:
      - $PWD:/home/gradle/project
      - gradle_home:/home/gradle/.gradle
  loan-api:
    image: gradle:jdk21-alpine
    command:
      - gradle
      - --no-daemon
      - clean
      - build
    working_dir: loan-api
    volumes:
      - $PWD:/home/gradle/project
      - gradle_home:/home/gradle/.gradle

volumes:
  gradle_home: