name: credit_module_challenge_build
services:
  config-server:
    image: gradle:jdk21-alpine
    command:
      - gradle
      - --no-daemon
      - clean
      - build
    volumes:
      - ./config-server:/home/gradle/project
      - config_server_gradle_home:/home/gradle/.gradle
    working_dir: /home/gradle/project
  loan-api:
    image: gradle:jdk21-alpine
    command:
      - gradle
      - --no-daemon
      - clean
      - build
    volumes:
      - ./loan-api:/home/gradle/project
      - loan_api_gradle_home:/home/gradle/.gradle
    working_dir: /home/gradle/project

volumes:
  config_server_gradle_home:
  loan_api_gradle_home: