name: credit_module_challenge_build
services:
  config-server:
    image: gradle:jdk21-alpine
    command:
      - gradle
      - --no-daemon
      - clean
      - build
      - --parallel
    volumes:
      - ./config-server:/home/gradle/project
      - gradle_home:/home/gradle/.gradle
    working_dir: /home/gradle/project
  loan-api:
    image: gradle:jdk21-alpine
    command:
      - gradle
      - --no-daemon
      - clean
      - build
      - --parallel
    volumes:
      - ./loan-api:/home/gradle/project
      - gradle_home:/home/gradle/.gradle
    working_dir: /home/gradle/project

volumes:
  gradle_home: