name: credit_module_challenge_build
services:
  config-server:
    image: gradle:jdk21-alpine
    command:
      - gradle
      - --no-daemon
      - -p
      - config-server
      - clean
      - build
    volumes:
      - $PWD/config-server:/home/gradle/project
      - gradle_home:/home/gradle/.gradle
  loan-api:
    image: gradle:jdk21-alpine
    command:
      - gradle
      - -p
      - loan-api
      - --no-daemon
      - clean
      - build
    volumes:
      - $PWD/loan-api:/home/gradle/project
      - gradle_home:/home/gradle/.gradle

volumes:
  gradle_home: