spring:
  security:
    user:
      name: user
      password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  datasource:
    username: loan_api
    password: password
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
loan-api:
  config:
    allowed-installments: 6, 9, 12, 24
    min-interest-rate: 0.10
    max-interest-rate: 0.50
    max-number-of-months-can-be-paid: 3
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false