spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/credit_module_challenge?currentSchema=loan_api
    driver-class-name: org.postgresql.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
