spring:
  security:
    user:
      name: user
      password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  datasource:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml