spring:
  datasource:
    url: jdbc:h2:mem:loan_api
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
        trace: false
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true