server:
  port: 8888
spring:
  security:
    user:
      name: user
      password: password
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          add-label-locations: false
          search-locations: file:config/{application}